### ISSUE TITLE
Update : New way without manual restore

### ISSUE THREAD

**Issue by nashv** [phuze/windows-10-missing-search-icons#3]
I fixed it by renaming the directory: 

C:\Users\{USER}\AppData\Local\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache\100

to something random. Try to Search something. This now blanks out the icons completely. 

After that, I cycle the Display scaling, starting Windows Search by typing something after every cycle. This jolts Windows Search to recreate the icon cache and a folder corresponding to your current resolution appears again.

Restart your computer, and Windows Search has rebuilt its icon set. All search icons appear again.

**Comment by juanmendez92** [comment]
Thank you! I tried to fix it several weeks and this worked perfectly

**Comment by phuze** [comment]
Hi @nashv thanks for the feedback. I've come across this suggestion over the years, and it is generally the experience of many, that it often proves ineffective. All the same, the last time I personally tried this method was when the search application was called `Microsoft.Windows.Cortana_cw5n1h2txyewy`, rather than `Microsoft.Windows.Search_cw5n1h2txyewy`. In fairness, it I considered it worth a try again.

I've tested this suggested solution. I can report that immediately upon renaming the folder, I noticed some system instability where the search window would not open on the first several clicks of the search icon. After having renamed this folder, cycling the desktop scaling and rebooting my system, I can confirm that Windows rebuilt the icon folder. However, icons were still missing while searching and found that it had no effect.

![image](https://user-images.githubusercontent.com/9218035/99887632-c9687900-2c13-11eb-8b18-50ad7fd276ab.png)
