### ISSUE TITLE
Upstream issues

### ISSUE THREAD

**Issue by claell** [phuze/windows-10-missing-search-icons#4]
I came across this project and think I am facing the same problem.

The current workaround approaches all seem to be either temporary or hacky. So I wondered whether there are upstream issues about this at Microsoft and Google. I really hope that there will be a sufficient solution in the long run that just works.

**Comment by phuze** [comment]
I've spent a significant number of weeks/days/hours trying to identify and resolve the issue beyond just "clearing icon caches and restarting Windows". I've created this information repository namely for my own purposes, but I thought it may help to share it with others. While it does not address the root problem, it's the only reliable way I've managed to resolve the issue.

From everything I've read, as I explained in the main readme, I believe its most likely related to the limitation with shell overlay icons in Windows. In a post by [Raymond Chen](https://devblogs.microsoft.com/oldnewthing/20190313-00/?p=101094), a long-time Windows developer, he explained that this shell limitation has existed since early Windows. In this article, he takes a deep dive into the difficulty in overcoming this limitation. Most notably, he calls attention to the design decision by the Windows team, in that they belief this functionality (shell icon overlays), simply shouldn't be used. It seems to me, that the Windows team has no plans now, or in the future, to address this.

While I have seen a number of posts within Microsoft's own bug/feedback communities about this issue, I do not see the responsibility being Microsoft's. I believe the issue here, is with Google. The simple fact is, Windows functions perfectly fine when you don't have Drive File Stream installed.

I think a large part of the challenge here, is Google's walled-off approach to community involvement. How do you even connect with the Google development team in any meaningful manner? Google has a history of imposing its will on the world, believing their methodologies or technologies are best. I fear that's perhaps what's going on here -- an unstoppable force has met an immovable object.

I think to sum it up, there's simply nothing we can do as the end user, to address the root issue, which exists within the implementation of the Drive File Stream program. I get the sense, from the lack of publicity for the product, that Google may have plans to [kill off Drive File Stream](https://killedbygoogle.com/) sometime in the future, so perhaps they simply don't feel the need to invest the time. Those this of course, is only my own speculation.

I think to summarize the answer to your question: No, there are no upstream issues with Google, because no channel exists through which the community can connect with the Google development team. Similarly, there are no upstream issues with Microsoft, because it's not a Microsoft related issue.

**Comment by claell** [comment]
I appreciate the work you have spent into this and that you shared it here.

I also rather think that Google has to address this. I read that it not only affects File Stream but also Backup and Sync, but not entirely sure about that.

For now I have misused their issue tracker to raise their awareness. It seems like that surprisingly worked and there now is an internal issue about this. For reference my issue: https://issuetracker.google.com/issues/173912342.

**Comment by phuze** [comment]
@claell This is great news! Thank you for sharing. I've included this in the README for others to find.

**Comment by claell** [comment]
Perfect! I am still not too optimistic currently, as we don't know how that issue progresses. But at least I hope Google devs are aware of it now.

I will close this issue then, since all relevant information is in the README now.
